uber-go/tally

example/main.go
scope.go
scope_test.go
stats.go

It is useful to the implementer to get notified of when the Scope just finished a bunch of work. They might choose to do nothing... but It is probably the case that you will want to flush a batch of data in a single network operation after Report is done, and it's way easier to add a Report method than to reimplement Scope.
@prashantv

Add Flush() method to the StatsReporter interface

---

scope_test.go

Using these wait groups allows us to reliably test the report loop running in a separate goroutine, and to ensure that the report calls actually get made the number of times we expect.

Better unit tests

---

scope_test.go
stats.go
stats_benchmark_test.go

This cuts BenchmarkTimerInterval from ~86ns to ~41ns
Seems reasonable to do while we have zero adoption.

Eliminate heap-allocation of Begin() timer function

---

scope.go
scope_test.go

Something that's required by uberfx for backwards compatibility support with old metrics system

Allow access to the underlying reporter

---

scope_test.go
stats.go
stats_benchmark_test.go
types.go

This makes timer.Stop() API a bit nicer to use. Plus now you have ability to just pass Stopwatch to some other function without passing timer as well.

Implement Stopwatch as struct for nicer elapsed time measurement.

---

Makefile
reporter.go
scope.go
scope_test.go
stats.go
stats_test.go

This PR adds a new method `NewCachedRootScope` and a new
`CachedReporter` interface.
This `CachedReporter` interface allows for onetime allocation
of counters, gauges & timers. This allows for the CachedReporter
to cached the tags map and do pre-computation.
The actual runtime interface after all the scopes & metrics are
allocated at startup just involves `ReportCount(int64)` and friends.
This enables a reporter backend to implement a more involved BUT
more performant interface.
I've got a benchmark using an internal reporter where I was measuring the
overhead of adding 3 timers to a HTTP server.
- master, 3 tally.Timers per request ~= 27% cpu overhead & 50 allocs per timer
- this branch, 3 tally.Timers per request ~= 11% cpu overhead & 25 allocs per timer
This is a 2x improvement and …

Add CachedReporter interface that supports pre allocation.

---

stats.go
stats_benchmark_test.go
types.go

It's still a little slower than the default `start := time.Now(); timer.Record(time.Since(start))` but it doesn't cause any allocations any longer.
```
$ go test -v -run none -bench BenchmarkTimerStopwatch -benchmem
BenchmarkTimerStopwatch-4       30000000                51.3 ns/op             0 B/op          0 allocs/op
PASS
ok      github.com/uber-go/tally        1.726s
$ go test -v -run none -bench BenchmarkTimerReport -benchmem
BenchmarkTimerReport-4          50000000                36.5 ns/op             0 B/op          0 allocs/op
PASS
ok      github.com/uber-go/tally        2.005s
```
cc @xichen2020 @akshayjshah @Raynos

Add zero allocation Stopwatch for both timer and histograms

---

scope.go
scope_test.go

There was the possibility a reporter might have `Flush` or any of the other report methods called on it after it had been closed itself.  This change fixes that possibility by holding a status lock during each report loop run.
cc @xichen2020

Fix possible flush after close semantics for scope

---

scope.go
scope_test.go

This PR addresses #34 by introducing a new function `uniqueID` which will create a unique ID for a metric using it fully qualified name and tags. This ID is then used as the key for the maps created `Snapshot` so that metrics with the same fully qualified names but different tags will not overwrite one another.

Use a unique ID for metrics returned from Snapshot

---

scope.go
scope_test.go
stats.go

As noted in #37, currently `Snapshot` doesn't capture histograms. Consequently, this PR adds histogram support to `Snapshot`.

Add histogram support to Snapshot

---

README.md

Because of the inline HTML, GitHub wasn't parsing the markdown correctly.
Inserting a newline fixes this.

Fix licence link by inserting newline

---

instrument.go
scope.go
scope_test.go
types.go

go-common's metric interface includes this functionality. It would be great to include it in tally as well since it simplifies application code, we don't need to explicitly handle timers and error cases every time we want to include metrics

Implement InstrumentedCall

---

instrument/call.go
instrument/call_test.go
instrument/types.go
scope_test.go
types.go

To reduce public API surface area from the base `tally` package.

Refactor InstrumentedCall to Call in instrument package

---

histogram.go
histogram_test.go

Summary: go's `sort.Sort` function will occasionally modify the data
that is passed into it even if that data is already sorted.
(https://play.golang.org/p/QJ8kiJzzVG)
For tally, this means that if a bucket slice is passed into tally, and
tally calls `sort.Sort` on that slice, the slice will get modified inline
(even if the list is already sorted).
In practice, this means that if a user is using a single slice of buckets
to create multiple tally histograms, there is a race condition where the
shared bucket object could be modified mid-histogram creation.
This PR creates copies of the []float64 and []time.Duration slices before
sorting them, guaranteeing that we won't have a race condition.

Copy Histogram Buckets before sorting

---

glide.lock
glide.yaml
m3/thriftudp/transport.go

Instead of relying on a pre-1.0 version of uber-go/atomic, this switches
to the 1.x series of go.uber.org/atomic.

Use go.uber.org/atomic ^1

---

glide.lock
glide.yaml
scope.go
stats.go

This is to fix the issues encountered in https://github.com/uber-go/tally/pull/60

Remove dependency on facebookgo/clock

---

glide.lock
glide.yaml

Apache Thrift made a breaking api change in the 0.11 series. This package relies on the ~0.10 API. 
Currently downstream packages using dep do not inherit this package's transitive dependency constraint on apache thrift because dep does not consider revision pins when importing constraints from alternate dependency managers. By using a semver range instead of a direct pin.
Another parallel path is to propose amending Dep to consider Glide revision pins as valid transitive constraints. We can do that unilaterally in our fork of dep but it would be much better if we worked with upstream. This pull request gets us out of the immediate pain and unblocks migration to dep within Uber.

Use semver dependency on Apache Thrift

---

m3/reporter_integration_test.go

There were some reporting metrics that haven't been flushed on program shutdown, this is likely due to program lifecycle however since this test is unable to reproduce the problem:
```
$ go test -v -run TestIntegrationProcessFlushOnExit -count 100
=== RUN   TestIntegrationProcessFlushOnExit
Test 0 emitted:
[Metric({Name:my-gauge MetricValue:MetricValue({Count:<nil> Gauge:<nil> Timer:TimerValue({I64Value:0xc000098980 DValue:<nil>})}) Timestamp:0xc000098990 Tags:map[]}) Me
tric({Name:my-counter MetricValue:MetricValue({Count:CountValue({I64Value:0xc0000989b8}) Gauge:<nil> Timer:<nil>}) Timestamp:0xc0000989c8 Tags:map[]}) Metric({Name:my-
gauge MetricValue:MetricValue({Count:<nil> Gauge:GaugeValue({I64Value:<nil> DValue:0xc0000989f0}) Timer:<nil>}) Timestamp:0xc000098a00 Tags:map[]})]
... …
```

Add integration test to test scope is flushed correctly for shortly lived programs 

---

prometheus/config.go
prometheus/reporter.go

This allows users to specifically enable which collectors they'd like if they are willing to use a non-default registry.

Add ability to use a non-default registry

---

prometheus/config.go
prometheus/config_test.go

This sets the correct error callback to use when a listen address conflict occurs with the Prometheus reporter, it will correctly panic/call whatever callback configured rather than experiencing a nil pointer panic.

Fix OnRegisterError not being called correctly when listen port in use

---

scope.go
scope_test.go

While changing backend reporting/batching settings, I noticed some very surprising behaviour, as if Flush() was called much more frequently than it should. Given the explicit reporting interval settings and Close() semantics, I would not expect Flush() to be called from each sub-scope, just from the root.
This PR moves the flush logic to reportRegistryWithLock(), so it's called only in the report loop or on root scope closure, so the underlying reporter does not do `$subscope_count` flushes every reporting cycle.

Flush reporter from root scope only

---

m3/config.go

Add HistogramBucketTagPrecision to m3 config to set the value while creating the new reporter.

Add HistogramBucketTagPrecision to m3 config

---

m3/customtransports/m3_calc_transport.go
m3/customtransports/m3_calc_transport_test.go
m3/reporter_benchmark_test.go

calculateSize uses a custom TTransport to count the number of
bytes without moving bytes around. However, since it's not a
TRichTransport, when used with TCompactProtocol, string field
writes cast to `[]byte`, and use the `Write` method.
By modifying TCalcTransport to implement TRichTransport, we can
avoid these allocations and speed up the calculation.
BenchmarkCalulateSize (no tags) comparison:
```
benchmark                    old ns/op     new ns/op     delta
BenchmarkCalulateSize-12     547           324           -40.77%
benchmark                    old allocs     new allocs     delta
BenchmarkCalulateSize-12     9              0              -100.00%
benchmark                    old bytes     new bytes     delta
BenchmarkCalulateSize-12     16            0             -100.00%
``` …

m3: Speed up calculateSize and reduce allocations

---

m3/reporter_benchmark_test.go
m3/thriftudp/transport.go
m3/thriftudp/transport_test.go

Similar to #116, emitting metrics requires allocations as TUDPTransport
does not implement TRichTransport, so we end up allocating to convert
`string` to `[]byte`.
Add a new benchmark BenchmarkEmitMetrics to measure the impact. This
change brings down allocations significantly:
```
benchmark                old ns/op     new ns/op     delta
BenchmarkEmitMetrics     119112        90897         -23.69%
benchmark                old allocs     new allocs     delta
BenchmarkEmitMetrics     1297           331            -74.48%
benchmark                old bytes     new bytes     delta
BenchmarkEmitMetrics     5284          3293          -37.68%
```

m3: Reduce allocations when emitting metrics

---

m3/customtransports/m3_calc_transport.go

The TCalcTransport is used by a single caller at a time, with a
mutex used to protect access:
https://github.com/uber-go/tally/blob/5431c04afc0bad76ce91ca3d549abb469abd2a10/m3/reporter.go#L400
The thrift generated code will only call `Write` serially, so there's no
need to use atomics here.
Removal of atomics gives a small performance improvement (10-15%):
```
> benchcmp -best old new
benchmark                 old ns/op     new ns/op     delta
BenchmarkCalulateSize     538           453           -15.80%
```

m3: Remove atomic from TCalcTransport

---

scope.go

Using `fmt.Sprintf` here is unnecessarily costly.

Use raw concat instead of fmt.Sprintf for fullyQualifiedName

---

scope.go
scope_benchmark_test.go

Optimize the cacheReport path for all Scopes.
Results for the added benchmark (master v HEAD):
```
benchmark                                  old ns/op      new ns/op     delta
BenchmarkScopeReporting/size1-4            79.6           42.0          -47.24%
BenchmarkScopeReporting/size10-4           201            62.3          -69.00%
BenchmarkScopeReporting/size100-4          1666           282           -83.07%
BenchmarkScopeReporting/size1000-4         16439          2547          -84.51%
BenchmarkScopeReporting/size10000-4        167362         26812         -83.98%
BenchmarkScopeReporting/size100000-4       4239618        328205        -92.26%
BenchmarkScopeReporting/size1000000-4      69189550       5549203       -91.98%
BenchmarkScopeReporting/size10000000-4     2205450363 …
```

Optimize Scope.cacheReport

---

key_gen.go
key_gen_test.go
scope.go
scope_benchmark_test.go
scope_registry.go

**Commits should be reviewed individually.**
This improves the performance of creating subscopes with new tags by
deferring merged map creation.
We currently create the merged map of tags first, and then calculate the
key which we use to determine if we have a cached subscope.
With this change, we calculate the key with slightly more complex logic
that inspects the unmerged maps and avoids paying the cost of merging
the maps if not needed.
To make this change, we first refactor scopeRegistry so that Scope
accesses it like a separate object.
---
I ran the benchmarks with `-count 3`.
**Before**
```
BenchmarkScopeTaggedCachedSubscopes-4             486406              2334 ns/op            1152 B/op          9 allocs/op
BenchmarkScopeTaggedCachedSubscopes-4             445890 …
```

subscoping: Defer tag merging

---

prometheus/config.go
prometheus/config_test.go

This PR will allow prometheus reporter listen on unix domain socket address. This is very useful when running under a situation when port conflicts occur often.
Currently, if specify a UDS address like `unix:/tmp/tally-metrics.sock` as listening address, reporter would fail to start as `http.ListenAndServe()` used by the reporter only support `tcp` network.

Allow Prometheus reporter listen on unix domain socket address

---

scope_test.go
stats.go

Make it idempotent to call `(*scope).Snapshot` multiple times during the same test case by using `(*counter).snapshot` instead of `(*counter).value` to capture the value of a Histogram during `Snapshot`. `value` changes the underlying value, `snapshot` does not.
https://github.com/uber-go/tally/issues/141

Don't change Histogram values during Snapshot

---

glide.lock
histogram.go
m3/customtransports/buffered_read_transport_test.go
m3/example/local_server.go
m3/reporter.go
m3/reporter_benchmark_test.go
m3/reporter_test.go
m3/resource_pool.go
m3/scope_test.go
m3/thriftudp/transport_test.go
stats.go

Histogram types are mutually exclusive, so there's no need to allocate storage for both types regardless of which type of bucket is provided.
Also includes some miscellaneous tweaks/cleanup.
At 100k histograms, this reduces their memory footprint by 45-65%, with diminishing returns of ~2% every 100k thereafter.

Make histogram allocations more efficient, general cleanup

---

histogram.go
internal/identity/accumulator.go
internal/identity/accumulator_benchmark_test.go
stats.go

This change further reduces histogram memory, primarily by reducing unnecessary (i.e. computationally inexpensive) histogram metadata like lookups and lower bounds.

Remove more unnecessary histogram storage redundancy

---

internal/cache/string_intern.go
internal/cache/tag_cache.go
m3/reporter.go
m3/scope_test.go

This change:
1. Introduces string interning for allocated metrics, including names and tag keys/values
2. Shares tags among metrics where possible
3. Introduces tag caching
4. Reduces histogram bucket allocations by reporting using closures instead of heap-allocating the buckets themselves

Share allocated tags among cached metrics

---

m3/reporter.go
m3/reporter_integration_test.go
m3/reporter_test.go
m3/scope_test.go
version.go

In addition to adding some useful internal tags, this also adds a Version constant (and tags the internal tags with it so that we can experiment with version tracking).

Add internal experimental metrics to M3 reporter

---

m3/reporter.go
m3/reporter_integration_test.go
m3/reporter_test.go
m3/scope_test.go

Previously, if reporting a very large number of metrics, some metrics could be silently dropped. Instead, block under the assumption that current benchmarks (which put throughput at anywhere between 1-3M reported metrics/sec) exceed real world use cases for the number of metrics reported within a given report cycle (e.g. we will never report >1M metrics every 1s).

Do not drop reported metrics when flush channel is full

---

go.mod
go.sum

From v3.1.1 to v3.2.1, https://github.com/cactus/go-statsd-client half-way moved to go mod and made the `statsd/` subdirectory a module in itself (granted they should have been using `/v3` path, but that came with later versions).
So this means across minor versions there is a mismatch between the `https://github.com/cactus/go-statsd-client` module and the `https://github.com/cactus/go-statsd-client/statsd` module. If you had the `https://github.com/cactus/go-statsd-client/statsd` module at v3.2.1 (i.e. https://github.com/cactus/go-statsd-client/commit/cb0885a1018c) and the latest tally library in your go mod and did a `go mod tidy`, on go 1.16 you break and on go 1.17 you get:
```
github.com/cretz/tally-sample imports
github.com/cactus/go-statsd-client/statsd loaded from …
```

Fix statsd dependency

---

m3/reporter.go

I don't know why packets were bounded to MTU before, but let's make the default sane and not tank performance for non-trivial metric counts, even if the users are not using a wrapper on top of Tally that does the right thing configuration-wise.

Bump default M3 packet size

---

glide.lock
glide.yaml
prometheus/reporter.go

Update vendored dependencies to pick up >3 years of changes, as upstream has fixed some issues with metric registration/validation.

Update Prometheus client

---

sanitize.go
sanitize_test.go

`ValidCharacters.sanitizeFn` constructs and throws away a `*bytes.Buffer`
for each sanitize call if any character needed to be sanitized.
The lifetime of this buffer is limited to just the scope of the sanitize
call. This is a very good candidate for pooling.
By pooling these buffers, we're able to bring down cost of sanitization
noticeably:
```
name                          old time/op    new time/op    delta
SanitizeFn-8                    79.0ns ± 0%    56.4ns ± 1%  -28.60%  (p=0.000 n=9+9)
SanitizedCounterAllocation-8     491ns ± 3%     446ns ± 3%   -9.21%  (p=0.000 n=10+10)
name                          old alloc/op   new alloc/op   delta
SanitizeFn-8                     64.0B ± 0%      8.0B ± 0%  -87.50%  (p=0.000 n=10+10)
SanitizedCounterAllocation-8      269B ± 0%      189B ± 2% …
```

ValidCharacters.sanitizeFn: Pool buffers

---

.github/workflows/test.yml

Set up a minimal CI check with GitHub workflows.
This is largely copy-pasted from Zap's CI check.
Depends on #178

Minimal CI setup

---

m3/reporter.go

We quickly start and stop process (it is wrapper for another command) and timeloop potentially can delay process shutdown by up-to 100ms (_timeResolution). Instead of just sleeping we as well wait for signal that shutdown is in progress and quickly terminate loop.

Terminate timeloop faster for m3

---

scope_test.go

This gives us unit test coverage for parallel usecases across multiple subscopes.

Test concurrent writes to reporter

---

internal/cache/tag_cache.go
m3/reporter.go
m3/reporter_integration_test.go
m3/reporter_test.go
m3/scope_test.go
scope.go
scope_registry.go
scope_registry_test.go
scope_test.go

Additional internal metrics will be emitted:
- `tally.internal.num-tag-cache` will report the number of tags
- `tally.internal.counter-cardinality` will report the number of counters across all scopes
- `tally.internal.gauge-cardinality` will report the number of gauges across all scopes
- `tally.internal.histogram-cardinality` will report the number of histograms across all scopes
Other changes:
- refactored tests to use internal metric counts defined in variables

Report Tag cache size as part of internal metrics (#189)

---

scope.go
scope_registry.go
scope_registry_test.go
scope_test.go

This addresses https://github.com/uber-go/tally/issues/198

fix broken internal metrics names and make them optional

---

scope.go
scope_registry.go
scope_registry_test.go
scope_test.go

Reverts uber-go/tally#203
Branch "master" has better testing and linting. Its changes will be rebased on top of v3 instead of parallel development.

Revert "fix broken internal metrics names and make them optional"

---

m3/reporter_integration_test.go
m3/scope_test.go
scope.go
scope_registry.go
scope_registry_test.go
scope_test.go

This resolves https://github.com/uber-go/tally/issues/198 and improves usability of the internal metrics toggle and mirrors the change in the v3 branch.

Fix for bad prometheus metrics name

---

m3/reporter_integration_test.go
m3/scope_test.go
scope.go
scope_registry.go
scope_registry_test.go
scope_test.go

This is a backport of https://github.com/uber-go/tally/commit/295c9c1dc22b905ff2ce727c770a27c3e2fc9b3c from branch master

Fix for bad prometheus metrics name (#205)

---

scope_registry.go
scope_registry_test.go
scope_test.go

This fixes an issue in ForEachScope() where a subscopeBucket could be updated during snapshot.

fixing race condition in ForEachScope

---

README.md
go.mod
go.sum
statsd/example/statsd_main.go
statsd/reporter.go

Current go-statsd-client is too old. Dependency commit is 2years ago.
https://github.com/cactus/go-statsd-client/tree/cb0885a1018c53bc05535cfbbd1fb858430b9f8c
It has a breaking change on `func NewReporter(statsd statsd.Statter, opts Options) tally.StatsReporter`.
Upgrade guide is just change like a following.
```diff
-	"github.com/cactus/go-statsd-client/statsd"
+	"github.com/cactus/go-statsd-client/v5/statsd"
```

update go-statsd-client to v5

---

scope.go
scope_registry.go
scope_registry_external_test.go

In #221 we ensure that closed scopes aren't returned by the registry.
However, because of how test scopes work, we need to keep them around in order to ensure that snapshots report the expected value, as those metrics are not accumulated outside of the scopes that are being closed.

TestScope: don't prune from registry when closed

---

scope.go
scope_test.go

Setting a default of 2s for now.

Set default reporting interval

---

.travis.yml

Doesn't make sense to test with ancient Go runtimes - generics are too sweet,
and `m3db/m3` is on 1.18.

Test with go >= 1.18

---

m3/reporter.go
m3/reporter_test.go

We want to avoid high cardinality on internal metrics due to host and instance tags.

redact host and instance tags for internal metrics

---

m3/example/m3_main.go
m3/reporter.go
m3/reporter_integration_test.go
m3/reporter_test.go
m3/scope_test.go
scope.go
scope_registry.go
scope_registry_test.go
scope_test.go

This revises what and how cardinality metrics are reported.
Changes:
- Cardinality data is emitted by default, as Gauge
- Names are now prefixed `tally.internal.` to be consistent with others
- Added scope cardinality data
- Cardinality metrics' tags are now consistent with reporter internal metrics

Revise internal cardinality metrics

---

scope_registry.go
scope_registry_test.go

Changes:
- Cached gauges will not be allocated if omitCardinalityMetrics is set to true

do not allocate gauge if cardinality metrics are turned off

---

scope_registry.go

```
WARNING: DATA RACE
Read at 0x00c000002568 by goroutine 13:
github.com/uber-go/tally/v4.(*scopeRegistry).reportInternalMetrics.func1()
/home/lukas-jenicek/Projects/Horizon/stack/vendor/github.com/uber-go/tally/v4/scope_registry.go:312 +0x89
github.com/uber-go/tally/v4.(*scopeRegistry).ForEachScope()
/home/lukas-jenicek/Projects/Horizon/stack/vendor/github.com/uber-go/tally/v4/scope_registry.go:159 +0x141
github.com/uber-go/tally/v4.(*scopeRegistry).reportInternalMetrics()
/home/lukas-jenicek/Projects/Horizon/stack/vendor/github.com/uber-go/tally/v4/scope_registry.go:310 +0x309
github.com/uber-go/tally/v4.(*scopeRegistry).CachedReport()
/home/lukas-jenicek/Projects/Horizon/stack/vendor/github.com/uber-go/tally/v4/scope_registry.go:137 +0x9c …
```

prevent race condition when reading from counters slice

---

scope_registry.go
scope_registry_test.go
scope_test.go

Previous attempt to fix it was incomplete - added a test that reliably triggers this.
Note that there was no need to track interm counts atomically, the subscope iterator is executed serially.
```
==================
WARNING: DATA RACE
Write at 0x00c000194588 by goroutine 8:
github.com/uber-go/tally/v4.(*scope).Gauge()
/Users/vytenis/go/tally/scope.go:341 +0x3a4
github.com/uber-go/tally/v4.TestCachedReporterInternalMetricsConcurrent.func2()
/Users/vytenis/go/tally/scope_registry_test.go:293 +0x114
Previous read at 0x00c000194588 by goroutine 9:
github.com/uber-go/tally/v4.(*scopeRegistry).reportInternalMetrics.func1()
/Users/vytenis/go/tally/scope_registry.go:314 +0xe0
github.com/uber-go/tally/v4.(*scopeRegistry).ForEachScope()
/Users/vytenis/go/tally/scope_registry.go:159 +0x118 …
```

Fix race when reporting internal cardinality metrics
