scope_test.go
stats_test.go

Some extra test code I've been working on.

More unit tests

---

.gitignore
README.md
example/main.go
reporter.go
scope.go
scope_benchmark_test.go
scope_test.go
stats.go
stats_test.go
statsd/options.go
statsd/reporter.go
statsd/reporter_test.go
types.go

cc @martin-mao @yurishkuro @xichen2020

Adjust root types for a little more flexibility when implementing Scope and other types

---

README.md
example/main.go
glide.lock
glide.yaml
prometheus/README.md
prometheus/reporter.go
prometheus/reporter_test.go
scope.go
scope_benchmark_test.go
scope_test.go
statsd/reporter.go
statsd/reporter_test.go

Adds a new reporter that supports the prometheus registry backend.

Add prometheus backend support

---

key_gen.go
pool.go
prometheus/README.md
prometheus/example/prometheus_main.go
prometheus/reporter.go
prometheus/reporter_test.go
scope.go

Return existing scopes when using Tagged and SubScope

---

multi/README.md
multi/reporter.go
multi/reporter_test.go
statsd/README.md
statsd/example/statsd_main.go
statsd/reporter.go
statsd/reporter_test.go

Add multi reporters to support multiple backends for a single scope

---

.gitignore
.travis.yml
Makefile
example/README.md
glide.lock
glide.yaml
m3/example/README.md
m3/example/config.yaml
m3/example/local_server.go
m3/example/m3_main.go
prometheus/example/README.md
statsd/example/README.md

Add M3 example using YAML config file

---

m3/reporter.go
m3/reporter_benchmark_test.go
m3/reporter_test.go

Addresses https://github.com/uber-go/tally/issues/45
cc @mcgourty @xichen2020 @martin-mao

Avoid send on channel when emitting values after closing an M3 reporter

---

README.md

cc @xichen2020 @prateek @jeromefroe

Clarify NewRootScope API with respect to race-safe usage and stopping reporting

---

histogram.go
histogram_test.go
scope_test.go

Change default histogram buckets from {-infinity,0} to {-infinity,first_defined}

---

prometheus/reporter.go

Passing the Gatherer is required to be able return the HTTPHandler
appropriate for a customer Registerer that is passed in. Without this
change, the HTTPHandler is *always* associated with the Gatherer for the
promhttp.DefaultRegisterer, which is confusing if a custom Registerer is
passed.

Add support for specifying 'Gatherer' in prometheus Reporter options.

---

glide.yaml

Pin dependencies to semver

---

scope.go

Fixes #111.
There's no real reason to attempt to hyper-optimize mutexes in this way; the cost of `defer` is negligible (for example, average counter allocation increased from 515ns to 580ns as part of this change) and the safety of deferring unlocks would be worth an even more substantial penalty.
Wherever this minor performance degradation would make a difference, metrics should be being cached anyway.

Simplify mutex use

---

glide.lock
glide.yaml
prometheus/reporter.go
prometheus/reporter_test.go
types.go

This contains the Prom-related bits from #112.

Add context/test for Tally<>Prometheus usage discrepancies

---

m3/config.go

Revert "Add HistogramBucketTagPrecision to m3 config"

---

scope_test.go

Fixes #113 - no need to rely on reporting loop to ensure flushes are performed only once, no matter how many sub-scopes were registered.

Make Test(Cached)ReporterFlushOnce test deterministic

---

README.md

A small variable name change in README.

Variable name change in README

---

m3/customtransports/buffered_read_transport_test.go
m3/customtransports/m3_calc_transport_test.go
m3/reporter_test.go
m3/thriftudp/transport_test.go

[NoError](https://godoc.org/github.com/stretchr/testify/require#NoError) is for asserting no error was return
[Error](https://godoc.org/github.com/stretchr/testify/require#Error) is for asserting an error was returned

use the testify functions for testing errors

---

scope.go
scope_registry.go
scope_test.go

This change enables using the `io.Closer` interface of `tally.Scope` to close and free a given subscope. It does not change the `tally.Scope` API; users must use type conversion to use this for now.
Additionally, this introduces the following behavior:
- closing the root scope closes all scopes
- closing a subscope only affects that subscope
Since there is no real "scope hierarchy", `Close()` is not cascading (outside of the root scope).

Enable indepent subscope closing through io.Closer

---

m3/reporter.go

Instead of allocating the temporary storage necessary to append histogram tags, borrow it from a pool.

Pool borrowed report-time histogram tags

---

m3/reporter.go

1ms is probably a bit aggressive, but 1s will be too low-resolution to not potentially conflate reported buckets. Instead, use 100ms.

Decrease M3 reporter time resolution from 1ms to 100ms

---

scope_registry.go

this resolves a linter issue for go 1.18

remove unused function

---

version.go

Changes
- incorporate bucketed subscopes from v3 (https://github.com/uber-go/tally/pull/191)

release version 4.1.4

---

scope_registry.go

This addresses https://github.com/uber-go/tally/issues/199

removing spammy message

---

scope_registry.go

#199 removed log printing

---

scope_registry.go
scope_registry_test.go
scope_test.go

This is a back port of https://github.com/uber-go/tally/pull/212

fixing race condition in ForEachScope

---

scope_registry_test.go
scope_test.go

Backport of #214
Changes:
* add goroutine leak checking in scope testing and fix goroutine leak

Add goleak checking to tests

---

version.go

Contains:
- new constructor to create RootScope with default reporting interval of 2s

update version to 4.1.8

---

.travis.yml
m3/config.go
m3/config_test.go
m3/reporter.go
m3/reporter_test.go
scope.go
scope_test.go
version.go

Merge changes from v4 branch into v3 and update version.go

Prepare v3.5.6

---

m3/reporter.go
m3/reporter_test.go

* redact host and instance tags for internal metrics
* fix unit test

redact host and instance tags for internal metrics (#237)

---

generate.go
m3/example/m3_main.go
m3/reporter.go
m3/reporter_integration_test.go
m3/reporter_test.go
m3/scope_test.go
scope.go
scope_registry.go
scope_registry_external_test.go
scope_registry_test.go
scope_test.go

Changes:
- Ported over changes from #241 and #243
- #243 is included because it contains test changes for #241

Sync v3 with master

---

scope_registry.go
scope_registry_test.go

port https://github.com/uber-go/tally/pull/246 to v3

backport of (#246)

---

stats.go
stats_test.go
types.go

This reverts commit e2a71ea0ab75eb085f65b326434cd2c1b8748955.

Revert "add possibility to record histogram with weight (#252)"
